### PR TITLE
WIP: "send to owners" test plan integration and spec

### PR DESCRIPTION
**Pull request by dexX7**
- ~~GroovyCSV needs to be integrated properly~~
- To get around issue #7, createFundedAddress uses an intermediate address, but does so, even when not necessary
- Invalidation tests are skipped
- ~~Tests involving reserved amounts are skipped~~ (update: only those involving meta DEx reservations)
- The Eval.me() in MSCSendToOwnersTestPlanSpec are aweful

### CODE REVIEW

**Comment by dexX7** [comment]
Here is the test report:
http://bitwatch.co/uploads/sto-test-plan-15ec9e8aa7/

I used the test description as label, whereby I believe it would be beneficial, if invalidation tests were highlighted explicitly:

http://bitwatch.co/uploads/sto-test-plan-15ec9e8aa7/classes/foundation.omni.test.rpc.sto.MSCSendToOwnersTestPlanSpec.html

Note: the test plan includes, but skipps, the tests involving reserved amounts that are currency *impossible* to pass due to the lack of meta DEx support.

Ping: @zathras-crypto

**Comment by msgilligan** [comment]
Looks great @dexX7 , but the JAR files should be downloaded by Gradle, not checked in to Git, right?

**Comment by dexX7** [comment]
Yes, this should be the way to go, but I didn't do the research to figure out how to.. :/

**Comment by dexX7** [comment]
Added support for reserved MSC/TMSC amounts. So now, only the invalidation tests are not fully integrated.

Should I remove the meta DEx tests from the test plan, or should they remain, but be skipped?

**Comment by msgilligan** [comment]
OK @dexX7 , I'll look in to adding the JAR files via `build.gradle` tomorrow.

**Comment by msgilligan** [comment]
Leave the meta DEx tests in as skipped for now, I'd say.

**Comment by msgilligan** [comment]
@dexX7  Do you mind going ahead and removing the JARs from this PR? If I can get the dependencies correct in `build.gradle`, I'll go ahead and merge it and add my fix on top.

**Comment by dexX7** [comment]
@msgilligan: done!
And it actually looks like it works for me now. Would be great, if you could confirm though.

**Comment by msgilligan** [comment]
Yes, working for me, too! IntelliJ seems flaky about picking up Gradle file changes. You need to make the correct incantations, but I'm not sure exactly which ones work.

**Comment by dexX7** [comment]
Awesome. :)

**Comment by msgilligan** [comment]
Note that the `groovycsv` dependency should be added with the `testCompile` method since it is only needed for the tests. I just fixed it: 200f96c02ad59c13b90f2e976bc560a96179a636.

See [Dependency Management Basics (http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html) for details.

(At some point we'll want to export some of the functions in this repository as separate JARs and we'll want to minimize transitive dependencies for those JARs)

**Pull request merged**
