### PR TITLE
Finalize "send to owners" test plan

### PR DESCRIPTION
**Pull request by dexX7**
- update some "when/then" labels
- rename TMSC to MSC as "main currency"
- use "true/false" instead of "1/0" for validity
- don't use Eval.me(), if the expected type is known in advance
- check transaction validity of "send to owners" transaction explicitly
- also confirm the reserved balances
- use "SPT" as short label for the property, similar to OmniChest
- fix expected reserved amounts (L44-45 in test plan)

### CODE REVIEW

**Comment by dexX7** [comment]
@msgilligan: the data type produced by GroovyCSV appears to be `String`, but it looks like this is not necessarily known by the IDE and the even more accurate approach would probably be: 
```groovy
mscAvailable = new BigDecimal(new String(data.MSCAvailable))
```

Now either way, what's currently not so nice is that the STO amounts are either `Integer`, `Long` or `BigDecimal`, depending on whether the amount is divisible or indivisible. In the best case, I'd like to get rid of all `Eval.me()`, but this requires knowledge about the expected type, which isn't given in this case.

What I also would like to improve is the following and alike:
```groovy
def ecosystem = new Ecosystem(data.Ecosystem as short)
```

... which makes me wonder, if we should introduce a `String` constructor for the "native" Omni data types such as `Ecosystem`, `CurrencyID` and `PropertyType`.

**Comment by marv-engine** [comment]
I mentioned this to @msgilligan this morning - I was confused about the meaning of the validity column. I thought it referred to the expected behavior, not whether the test is ready to run. I suggest renaming the validity column to be something like run_test, so it's clear that it specifies whether or not to run each test.

**Comment by dexX7** [comment]
It will be used to confirm the expected validity, but at this point the framework isn't not yet fully suitable to handle invalid transactions. Skipping tests based on expected validity is just a workaround at the very moment.

I'm thinking about how it could be done in a data driven manner though, and I had in mind to add/rename some columns to end up with something like:

```
CreateNewProperty | ... | STOCurrencyID

false             | ... | 0                 << for "STO property is 0 (bitcoin)"
false             | ... | 4294967295        << for "STO Property ID is non-existent"

true              | ... | ?                 << for all tests where a new property is created
```

**Comment by dexX7** [comment]
At this point I believe adding a `CreateNewProperty` field is not the way to go, because there are only two tests where it would be `false` - one involving BTC and one involving a non-existing property.

It turns out those cases are very special to begin with, because other methods such as `getbalance_MP` and `send_MP` don't work with BTC or non-existing properties.

**Comment by msgilligan** [comment]
Hi @dexX7 , I'll take a closer look at this one tomorrow. Let me know via email if there's anything you can't wait for.

**Comment by dexX7** [comment]
@msgilligan: sure, no hurry. I'm testing and updating this one probably anyway, or maybe combine this one with the invalidation tests.

**Comment by msgilligan** [comment]
Looks like after I merged #24 this one can no longer be automatically merged.

**Comment by dexX7** [comment]
No problem, I'll update soon.

**Comment by dexX7** [comment]
Okay, I didn't clean up yet or build upon master, but it would be great, if you could take a look @msgilligan:

- All tests except three, and the meta DEx tests, are tested
- The tests can run twice: once while using "sendtoowners_MP" and once with "sendrawtx_MP"
- Transaction validity is checked
- Exceptions can be expected

I added a new column named "Exceptional" to the test plan for the last point.

Test report: http://bitwatch.co/uploads/sto-test-plan-5bb69c0/ (not sure where the null is coming from)
[.../sto-test-plan-5bb69c0/classes/foundation.omni.test.rpc.sto.MSCSendToOwnersTestPlanSpec.html](http://bitwatch.co/uploads/sto-test-plan-5bb69c0/classes/foundation.omni.test.rpc.sto.MSCSendToOwnersTestPlanSpec.html) :)

Right now Master Core throws exceptions in the following tests and I changed the test plan to match this behavior:

"Sender available balance = 0, reserved balance = 0 for the STO property"
"Sender available balance = 0, reserved balance > 0 for the STO property"
"Sender STO amount exceeds the number owned and available by the sending address, reserved balance > 0"
"STO Property ID is non-existent"
"STO Property ID is 0 (bitcoin)"

It's debatable, whether those exceptions are good or bad here, or if some are missing in other tests, but I think would be material for another issue/a broader topic to discuss.

**Comment by dexX7** [comment]
Build on master, and splitted such that changes to the test plan are visible, when comparing [ca446a4](https://github.com/dexX7/bitcoin-spock/commit/ca446a4230d5b0dc5f51459e7364f4b303e072be).

**Comment by msgilligan** [comment]
@dexX7 Is this PR ready for merging?

**Pull request merged**
